version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/app"
    target-branch: "dev"
    schedule:
      interval: "weekly"
