name: "Publish js packages"

on:
  push:
    branches:
      - main

jobs:
  publish_npm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
          registry-url: "https://registry.npmjs.org"
          scope: "@avalabs"
      - name: Install yarn
        run: npm install -g yarn
      - name: Create .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc
      - name: Build package
        run: |
          cd js
          yarn install
          yarn build
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH_AUTO }}
        run: npx semantic-release
