name: "Publish js packages"

on:
  push:
    branches:
      - main

jobs:
  publish_npm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
          registry-url: "https://registry.npmjs.org"
          scope: "@zondax"
      - name: Install yarn
        run: npm install -g yarn
      - name: Build package
        run: |
          cd js
          yarn install
          yarn build
      - name: release
        run: npx semantic-release
